<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="4" total="5" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="31006" started-at="2019-04-20T04:36:03Z" finished-at="2019-04-20T04:36:34Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="31006" started-at="2019-04-20T04:36:03Z" finished-at="2019-04-20T04:36:34Z">
      <class name="com.test.phptravelsUser.TestSuit1">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.test.phptravelsUser.TestSuit1@20322d26]" name="beforeClass" is-config="true" duration-ms="866" started-at="2019-04-20T04:36:03Z" finished-at="2019-04-20T04:36:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="launchBrowser(java.lang.reflect.Method, [Ljava.lang.Object;)[pri:0, instance:com.test.phptravelsUser.TestSuit1@20322d26]" name="launchBrowser" is-config="true" duration-ms="13344" started-at="2019-04-20T04:36:04Z" finished-at="2019-04-20T04:36:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[void com.test.phptravelsUser.TestSuit1.testCase1()]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[Ljava.lang.Object;@3b2c0e88]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="FAIL" signature="testCase1()[pri:0, instance:com.test.phptravelsUser.TestSuit1@20322d26]" name="testCase1" duration-ms="13539" started-at="2019-04-20T04:36:18Z" finished-at="2019-04-20T04:36:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [www.phptravels.net] but found [PHPTRAVELS | Travel Technology Partner]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [www.phptravels.net] but found [PHPTRAVELS | Travel Technology Partner]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.test.phptravelsUser.TestSuit1.testCase1(TestSuit1.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase1 -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.test.phptravelsUser.TestSuit1@20322d26]" name="tearDown" is-config="true" duration-ms="2131" started-at="2019-04-20T04:36:31Z" finished-at="2019-04-20T04:36:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testCase1 status=FAILURE method=TestSuit1.testCase1()[pri:0, instance:com.test.phptravelsUser.TestSuit1@20322d26] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="generateLog()[pri:0, instance:com.test.phptravelsUser.TestSuit1@20322d26]" name="generateLog" is-config="true" duration-ms="1062" started-at="2019-04-20T04:36:33Z" finished-at="2019-04-20T04:36:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generateLog -->
      </class> <!-- com.test.phptravelsUser.TestSuit1 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
